import Link from "next/link";
import { Icon } from "@/components/ui/icon";

export default function HomePage() {
  return <main className="marketing">
    <nav className="marketing-nav"><Link href="/" className="brand dark"><span className="brand-mark">V</span><span><b>Vigie</b><small>conformité RH</small></span></Link><div><a href="#produit">Produit</a><a href="#methode">Méthode</a><Link className="btn secondary small" href="/dashboard">Voir la démo</Link></div></nav>
    <section className="hero"><div className="hero-copy"><div className="pill"><span className="live-dot"/> Moteur de règles · France</div><h1>Le droit au travail,<br/><em>sans angle mort.</em></h1><p>Vigie transforme les règles applicables aux salariés étrangers en parcours opérationnels pour les employeurs : recruter, renouveler, modifier ou rompre — avec les sources à chaque étape.</p><div className="hero-actions"><Link className="btn primary large" href="/analyse">Analyser une situation <Icon name="arrow"/></Link><Link className="btn ghost large" href="/dashboard">Explorer le produit</Link></div><div className="hero-proof"><span><Icon name="check"/> Règles versionnées</span><span><Icon name="check"/> Sources officielles</span><span><Icon name="check"/> Zéro verdict LLM</span></div></div><div className="hero-panel"><div className="browser-chrome"><span/><span/><span/><small>app.vigie-rh.fr/analyse</small></div><div className="demo-screen"><div className="demo-top"><span className="demo-logo">V</span><div><small>Diagnostic recrutement</small><strong>Candidate · Maroc</strong></div><span className="badge badge-warning">Sous conditions</span></div><div className="demo-result"><p>Peut commencer aujourd'hui ?</p><strong>NON</strong><small>Une autorisation de travail doit être instruite avant la prise de poste.</small></div><div className="demo-steps"><div className="done">✓ <span>Nationalité et titre contrôlés</span></div><div className="current">2 <span>Vérifier la situation de l'emploi</span></div><div>3 <span>Déposer l'autorisation de travail</span></div><div>4 <span>Établir le droit au travail</span></div></div><div className="demo-source"><Icon name="book"/><span>Code du travail · R. 5221-1</span><Icon name="external"/></div></div></div></section>
    <section className="logo-strip"><span>Pour les</span><strong>DRH</strong><strong>PME</strong><strong>Experts-comptables</strong><strong>Cabinets conseil</strong><strong>Avocats</strong></section>
    <section id="produit" className="marketing-section"><div className="section-intro"><p className="eyebrow">Un seul cockpit</p><h2>De la question RH au plan d'action sourcé.</h2><p>Le produit est conçu autour des décisions réelles de l'employeur, pas autour d'une bibliothèque de fiches.</p></div><div className="feature-grid"><Feature icon="scan" title="Decision Engine" text="Un questionnaire court transforme la situation en diagnostic, conditions, blocages et checklist."/><Feature icon="users" title="Portefeuille salarié" text="Dates d'expiration, documents, relances et historique réunis dans un dossier unique."/><Feature icon="shield" title="Audit conformité" text="Visualisez les dossiers incomplets et les échéances critiques avant qu'elles ne deviennent des incidents."/><Feature icon="book" title="Sources versionnées" text="Chaque conclusion renvoie vers une source officielle avec date d'effet et date de revue."/></div></section>
    <section id="methode" className="method-section"><div><p className="eyebrow">Architecture de confiance</p><h2>L'IA lit. Le moteur de règles décide.</h2><p>Une future extraction documentaire peut reconnaître un type de titre ou une date. Mais elle ne choisit jamais la règle juridique. Les décisions restent déterministes, testables et auditables.</p></div><div className="method-flow"><span>Document</span><b>→</b><span>Extraction</span><b>→</b><strong>Moteur juridique</strong><b>→</b><span>Sources</span><b>→</b><span>Plan d'action</span></div></section>
    <footer className="marketing-footer"><div className="brand dark"><span className="brand-mark">V</span><span><b>Vigie</b><small>conformité RH</small></span></div><p>Prototype produit — contenu juridique à valider avant mise en production.</p><Link href="/dashboard">Ouvrir la démo →</Link></footer>
  </main>;
}

function Feature({ icon, title, text }: { icon: Parameters<typeof Icon>[0]["name"]; title: string; text: string }) { return <article className="feature-card"><span><Icon name={icon}/></span><h3>{title}</h3><p>{text}</p></article>; }
