import type { LegalSource } from "./types";

export const legalSources: Record<string, LegalSource> = {
  "ct-r5221-1": {
    id: "ct-r5221-1",
    title: "Code du travail — article R. 5221-1",
    authority: "legifrance",
    url: "https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000049999770/",
    effectiveFrom: "2024-09-01",
    lastReviewed: "2026-09-09",
    note: "Principe de l'autorisation de travail, demande par l'employeur et nouvelle demande pour tout nouveau contrat.",
  },
  "ct-r5221-2": {
    id: "ct-r5221-2",
    title: "Code du travail — article R. 5221-2",
    authority: "legifrance",
    url: "https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000043323648/",
    effectiveFrom: "2026-04-26",
    lastReviewed: "2026-09-09",
    note: "Dispenses d'autorisation de travail, avec catégories et sous-catégories précisément énumérées.",
  },
  "ct-r5221-20": {
    id: "ct-r5221-20",
    title: "Code du travail — article R. 5221-20",
    authority: "legifrance",
    url: "https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000049999760/",
    effectiveFrom: "2024-09-01",
    lastReviewed: "2026-09-09",
    note: "Critères de délivrance : emploi proposé, situation de l'employeur, profession réglementée, rémunération et cas particuliers.",
  },
  "ct-r5221-27": {
    id: "ct-r5221-27",
    title: "Code du travail — article R. 5221-27",
    authority: "legifrance",
    url: "https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000043320735/",
    effectiveFrom: "2021-04-01",
    lastReviewed: "2026-09-09",
    note: "Déclaration nominative préalable de l'embauche d'un étudiant étranger, au moins deux jours ouvrables avant la date d'effet.",
  },
  "ct-r5221-41": {
    id: "ct-r5221-41",
    title: "Code du travail — article R. 5221-41",
    authority: "legifrance",
    url: "https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000043320795/",
    effectiveFrom: "2021-04-01",
    lastReviewed: "2026-09-09",
    note: "Vérification par l'employeur de la régularité du séjour auprès du préfet avant l'embauche.",
  },
  "ct-r5221-42": {
    id: "ct-r5221-42",
    title: "Code du travail — article R. 5221-42",
    authority: "legifrance",
    url: "https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000043320792/",
    effectiveFrom: "2021-04-01",
    lastReviewed: "2026-09-09",
    note: "Saisine au moins deux jours ouvrables avant l'embauche et délai de réponse du préfet.",
  },
  "ct-r5221-43": {
    id: "ct-r5221-43",
    title: "Code du travail — article R. 5221-43",
    authority: "legifrance",
    url: "https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000043320787/",
    effectiveFrom: "2021-04-01",
    lastReviewed: "2026-09-09",
    note: "Exception aux vérifications R. 5221-41 et R. 5221-42 lorsque l'étranger produit notamment un justificatif d'inscription sur la liste des demandeurs d'emploi.",
  },
  "ceseda-r431-15-1": {
    id: "ceseda-r431-15-1",
    title: "CESEDA — article R. 431-15-1",
    authority: "legifrance",
    url: "https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000043288895/",
    effectiveFrom: "2021-05-01",
    lastReviewed: "2026-09-09",
    note: "L'attestation dématérialisée de dépôt en ligne ne justifie pas la régularité du séjour ; attestation de prolongation si l'instruction dépasse la validité du titre, sous conditions.",
  },
  "ceseda-r431-15-2": {
    id: "ceseda-r431-15-2",
    title: "CESEDA — article R. 431-15-2",
    authority: "legifrance",
    url: "https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000051747524/",
    effectiveFrom: "2025-06-16",
    lastReviewed: "2026-09-09",
    note: "Une attestation de prolongation d'instruction d'un renouvellement d'une carte permettant une activité professionnelle autorise cette activité en France métropolitaine.",
  },
  "ceseda-l433-3": {
    id: "ceseda-l433-3",
    title: "CESEDA — article L. 433-3",
    authority: "legifrance",
    url: "https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000042776360/",
    effectiveFrom: "2021-05-01",
    lastReviewed: "2026-09-09",
    note: "Continuité de séjour et de droit au travail pendant trois mois pour certaines catégories précises, dont la carte de résident, lors du renouvellement ; le second alinéa plus large a cessé d'être applicable selon le Conseil d'État le 26 juin 2025.",
  },
  "sp-autorisation-travail": {
    id: "sp-autorisation-travail",
    title: "Service-Public — Autorisation de travail d'un salarié étranger en France",
    authority: "service-public",
    url: "https://www.service-public.fr/particuliers/vosdroits/F2728",
    lastReviewed: "2026-09-09",
    note: "Fiche vérifiée le 18 juin 2026 : titres, étudiants, documents provisoires, renouvellement de l'autorisation de travail et maintien du droit au travail.",
  },
  "arrete-metiers-2025": {
    id: "arrete-metiers-2025",
    title: "Arrêté du 21 mai 2025 — métiers et zones en tension",
    authority: "legifrance",
    url: "https://www.legifrance.gouv.fr/loda/id/JORFTEXT000051643488/",
    effectiveFrom: "2025-05-23",
    lastReviewed: "2026-09-09",
  },
  "sp-sanctions": {
    id: "sp-sanctions",
    title: "Service-Public — Conséquences de l'emploi sans autorisation de travail",
    authority: "service-public",
    url: "https://www.service-public.fr/particuliers/vosdroits/F33886",
    lastReviewed: "2026-09-09",
    note: "Fiche vérifiée le 1er juin 2026.",
  },
};

export function getSources(ids: string[]): LegalSource[] {
  return [...new Set(ids)].map((id) => legalSources[id]).filter(Boolean);
}
