import type { LegalRule } from "../types";

export const baseRules: LegalRule[] = [
  {
    id: "fr-national",
    version: 1,
    description: "La procédure travailleurs étrangers ne s'applique pas à un ressortissant français.",
    effectiveFrom: "2024-09-01",
    lastReviewed: "2026-09-09",
    sourceIds: ["ct-r5221-1"],
    priority: 200,
    applies: ({ input }) => input.nationalityGroup === "france",
    evaluate: () => ({
      patches: {
        canWorkNow: true,
        workAuthorization: "not_applicable",
        employerVerification: "not_applicable",
        employmentSituation: "not_applicable",
        shortageOccupation: "not_applicable",
        confidence: "high",
      },
      forceStatus: "clear",
      findings: [{
        id: "france",
        title: "Hors champ travailleurs étrangers",
        detail: "Aucune autorisation de travail liée au statut d'étranger n'est à instruire dans ce parcours.",
        severity: "success",
        sourceIds: ["ct-r5221-1"],
      }],
    }),
  },
  {
    id: "eu-free-movement",
    version: 1,
    description: "UE/EEE/Suisse : dispense d'autorisation de travail.",
    effectiveFrom: "2026-04-26",
    lastReviewed: "2026-09-09",
    sourceIds: ["ct-r5221-2"],
    priority: 190,
    applies: ({ input }) => input.nationalityGroup === "eu_eea_swiss",
    evaluate: () => ({
      patches: {
        canWorkNow: true,
        workAuthorization: "no",
        employerVerification: "not_applicable",
        employmentSituation: "not_applicable",
        shortageOccupation: "not_applicable",
        confidence: "high",
      },
      forceStatus: "clear",
      findings: [{
        id: "eu-exempt",
        title: "Autorisation de travail non requise",
        detail: "Les ressortissants UE/EEE/Suisse sont dispensés de l'autorisation de travail prévue à l'article R. 5221-1, sous réserve des conditions propres à leur droit au séjour.",
        severity: "success",
        sourceIds: ["ct-r5221-2"],
      }],
      checklist: [{
        id: "identity",
        label: "Conserver le justificatif d'identité et de nationalité",
        status: "todo",
        sourceIds: ["ct-r5221-2"],
      }],
    }),
  },
  {
    id: "algerian-special-regime",
    version: 1,
    description: "Le régime franco-algérien nécessite une branche dédiée.",
    effectiveFrom: "2024-09-01",
    lastReviewed: "2026-09-09",
    sourceIds: ["sp-autorisation-travail"],
    priority: 195,
    applies: ({ input }) => input.nationalityGroup === "algeria",
    evaluate: () => ({
      forceStatus: "review_required",
      patches: {
        canWorkNow: null,
        workAuthorization: "review",
        employerVerification: "review",
        employmentSituation: "review",
        shortageOccupation: "review",
        confidence: "low",
      },
      findings: [{
        id: "algeria-review",
        title: "Régime spécial à vérifier",
        detail: "Le régime des ressortissants algériens obéit à des règles particulières. Le moteur bloque volontairement la conclusion automatique tant que ce corpus n'est pas modélisé.",
        severity: "warning",
        sourceIds: ["sp-autorisation-travail"],
      }],
      checklist: [{
        id: "special-regime",
        label: "Faire vérifier le régime franco-algérien applicable",
        status: "attention",
        sourceIds: ["sp-autorisation-travail"],
      }],
    }),
  },
  {
    id: "private-family-generic-review",
    version: 1,
    description: "Une catégorie VPF générique ne suffit pas à identifier automatiquement la dispense applicable.",
    effectiveFrom: "2026-04-26",
    lastReviewed: "2026-09-09",
    sourceIds: ["ct-r5221-2"],
    priority: 160,
    applies: ({ input }) => input.nationalityGroup === "third_country" && input.permitType === "private_family",
    evaluate: () => ({
      forceStatus: "review_required",
      patches: { canWorkNow: null, workAuthorization: "review", employerVerification: "review", confidence: "low" },
      findings: [{
        id: "private-family-review",
        title: "Sous-catégorie « vie privée et familiale » à préciser",
        detail: "L'article R. 5221-2 vise plusieurs fondements de cartes « vie privée et familiale », avec des conditions qui ne sont pas identiques. Sans fondement exact, le moteur ne déduit pas automatiquement une dispense.",
        severity: "warning",
        sourceIds: ["ct-r5221-2"],
      }],
      checklist: [{
        id: "private-family-basis",
        label: "Identifier le fondement exact et la mention du titre VPF",
        status: "attention",
        sourceIds: ["ct-r5221-2"],
      }],
    }),
  },
  {
    id: "talent-generic-review",
    version: 1,
    description: "La catégorie Talent générique doit être qualifiée avant de déduire une dispense.",
    effectiveFrom: "2026-04-26",
    lastReviewed: "2026-09-09",
    sourceIds: ["ct-r5221-2", "sp-autorisation-travail"],
    priority: 160,
    applies: ({ input }) => input.nationalityGroup === "third_country" && input.permitType === "talent",
    evaluate: () => ({
      forceStatus: "review_required",
      patches: { canWorkNow: null, workAuthorization: "review", employerVerification: "review", confidence: "low" },
      findings: [{
        id: "talent-review",
        title: "Périmètre du titre Talent à préciser",
        detail: "La carte Talent dispense en principe l'employeur d'une autorisation de travail distincte pour l'activité qu'elle autorise. Le formulaire actuel ne qualifie pas encore la sous-catégorie et la correspondance entre cette activité et le poste envisagé : le moteur reste donc en revue complémentaire.",
        severity: "warning",
        sourceIds: ["ct-r5221-2", "sp-autorisation-travail"],
      }],
      checklist: [{
        id: "talent-basis",
        label: "Identifier la sous-catégorie Talent et vérifier que l'activité envisagée correspond au titre",
        status: "attention",
        sourceIds: ["ct-r5221-2", "sp-autorisation-travail"],
      }],
    }),
  },
  {
    id: "resident-permit-exempt",
    version: 1,
    description: "Carte de résident : dispense d'autorisation de travail distincte dans le périmètre modélisé.",
    effectiveFrom: "2026-04-26",
    lastReviewed: "2026-09-09",
    sourceIds: ["ct-r5221-2"],
    priority: 150,
    applies: ({ input }) => input.nationalityGroup === "third_country" && input.permitType === "resident",
    evaluate: () => ({
      patches: { canWorkNow: true, workAuthorization: "no", confidence: "high" },
      findings: [{
        id: "resident-exempt",
        title: "Autorisation de travail distincte non requise",
        detail: "La carte de résident visée par l'article R. 5221-2 est dispensée de l'autorisation de travail prévue à l'article R. 5221-1, sous réserve de la validité et de l'authenticité du document.",
        severity: "success",
        sourceIds: ["ct-r5221-2"],
      }],
    }),
  },
  {
    id: "hire-prefecture-verification-france-travail-exempt",
    version: 1,
    description: "Justificatif d'inscription France Travail : exception aux vérifications R. 5221-41 et R. 5221-42.",
    effectiveFrom: "2021-04-01",
    lastReviewed: "2026-09-09",
    sourceIds: ["ct-r5221-43", "sp-autorisation-travail"],
    priority: 145,
    applies: ({ input }) => input.action === "hire"
      && input.nationalityGroup === "third_country"
      && input.location === "france"
      && input.registeredWithFranceTravail === true,
    evaluate: () => ({
      patches: { employerVerification: "no" },
      findings: [{
        id: "prefecture-verification-france-travail-exempt",
        title: "Vérification préfectorale non requise dans le cas déclaré",
        detail: "La personne est déclarée comme produisant un justificatif d'inscription sur la liste des demandeurs d'emploi France Travail. L'article R. 5221-43 écarte alors les vérifications prévues aux articles R. 5221-41 et R. 5221-42.",
        severity: "success",
        sourceIds: ["ct-r5221-43", "sp-autorisation-travail"],
      }],
      checklist: [{
        id: "archive-france-travail-proof",
        label: "Archiver le justificatif d'inscription France Travail",
        status: "todo",
        sourceIds: ["ct-r5221-43"],
      }],
    }),
  },
  {
    id: "hire-prefecture-verification-unknown",
    version: 1,
    description: "Le moteur ne tranche pas la vérification préfectorale si l'exception France Travail n'est pas renseignée.",
    effectiveFrom: "2021-04-01",
    lastReviewed: "2026-09-09",
    sourceIds: ["ct-r5221-41", "ct-r5221-42", "ct-r5221-43"],
    priority: 145,
    applies: ({ input }) => input.action === "hire"
      && input.nationalityGroup === "third_country"
      && input.location === "france"
      && typeof input.registeredWithFranceTravail !== "boolean",
    evaluate: () => ({
      forceStatus: "review_required",
      patches: { employerVerification: "review", confidence: "low" },
      findings: [{
        id: "prefecture-verification-unknown",
        title: "Exception France Travail à renseigner",
        detail: "Le moteur doit savoir si la personne produit un justificatif d'inscription sur la liste des demandeurs d'emploi avant de conclure sur l'obligation de vérification préfectorale.",
        severity: "warning",
        sourceIds: ["ct-r5221-41", "ct-r5221-42", "ct-r5221-43"],
      }],
    }),
  },
  {
    id: "hire-prefecture-verification",
    version: 3,
    description: "Avant l'embauche en France, hors exception modélisée, l'employeur vérifie la régularité du séjour auprès du préfet.",
    effectiveFrom: "2021-04-01",
    lastReviewed: "2026-09-09",
    sourceIds: ["ct-r5221-41", "ct-r5221-42", "ct-r5221-43", "sp-autorisation-travail"],
    priority: 140,
    applies: ({ input }) => input.action === "hire"
      && input.nationalityGroup === "third_country"
      && input.location === "france"
      && input.registeredWithFranceTravail === false,
    evaluate: ({ input }) => ({
      patches: { employerVerification: "yes" },
      findings: [{
        id: "prefecture-verification",
        title: input.employerVerificationCompleted === true ? "Vérification préfectorale déclarée accomplie" : "Vérification préfectorale à accomplir",
        detail: input.employerVerificationCompleted === true
          ? "La vérification préalable est déclarée comme accomplie. Conservez la preuve de la saisine et de la réponse, ou de l'expiration du délai applicable."
          : "L'employeur doit effectuer la vérification préalable selon la procédure applicable. L'article R. 5221-42 prévoit une saisine au moins deux jours ouvrables avant la date d'effet de l'embauche.",
        severity: input.employerVerificationCompleted === true ? "success" : "info",
        sourceIds: ["ct-r5221-41", "ct-r5221-42", "sp-autorisation-travail"],
      }],
      checklist: [{
        id: "verify-prefecture",
        label: "Effectuer la vérification préfectorale avant l'embauche",
        description: "À anticiper au moins deux jours ouvrables avant la date effective d'embauche.",
        status: input.employerVerificationCompleted === true ? "done" : "todo",
        sourceIds: ["ct-r5221-41", "ct-r5221-42", "sp-autorisation-travail"],
      }],
    }),
  },
  {
    id: "third-country-principle",
    version: 1,
    description: "Principe d'autorisation de travail pour les ressortissants de pays tiers.",
    effectiveFrom: "2024-09-01",
    lastReviewed: "2026-09-09",
    sourceIds: ["ct-r5221-1", "sp-autorisation-travail"],
    priority: 50,
    applies: ({ input }) => input.nationalityGroup === "third_country",
    evaluate: ({ input }) => ({
      checklist: [
        {
          id: "verify-title",
          label: "Vérifier le document autorisant le séjour et/ou le travail",
          status: "todo",
          sourceIds: ["sp-autorisation-travail"],
        },
        {
          id: "archive-proof",
          label: "Archiver la preuve des contrôles dans le dossier salarié",
          status: "todo",
          sourceIds: ["sp-autorisation-travail"],
        },
      ],
      findings: input.newContract ? [{
        id: "new-contract",
        title: "Nouveau contrat détecté",
        detail: "Le moteur réévalue l'exigence d'autorisation de travail pour ce nouveau contrat.",
        severity: "info",
        sourceIds: ["ct-r5221-1"],
      }] : [],
    }),
  },
];
